[Docs] Doc about using CombinedDataset
open-mmlab/mmpose pull request #2025
Opened 2023-03-07 08:14 UTC by Ben-Louis

## Motivation

## Modification

## BC-breaking (Optional)

## Use cases (Optional)

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-03-07 08:34 UTC, Tau-J commented on docs/en/advanced_guides/mixed_datasets.md
> +Next, we will discuss two methods of mixing datasets.
```suggestion
Next, we will discuss two methods of mixing datasets.
- [Merge](#-merge-aic-into-coco-) 
- [Combine](#-combine-arc-and-coco-)
```

2023-03-10 07:26 UTC, Tau-J requested changes

2023-03-10 07:26 UTC, Tau-J commented on docs/en/advanced_guides/mixed_datasets.md
> +    type='COCODataset',
```suggestion
    type='CocoDataset',
```

2023-03-10 07:26 UTC, Tau-J commented on docs/zh_cn/advanced_guides/mixed_datasets.md
> +    type='COCODataset',
```suggestion
    type='CocoDataset',
```

2023-03-10 07:26 UTC, Tau-J commented on docs/zh_cn/advanced_guides/mixed_datasets.md
> +    type='COCODataset',
```suggestion
    type='CocoDataset',
```

2023-03-10 07:26 UTC, Tau-J commented on docs/en/advanced_guides/mixed_datasets.md
> +    type='COCODataset',
```suggestion
    type='CocoDataset',
```

2023-03-10 09:10 UTC, ly015 approved these changes

2023-03-10 09:11 UTC, merged